### ISSUE TITLE
How to use this module without exchange?

### ISSUE THREAD

**Issue by bee395** [financelurker/crypto-trades-firefly-iii#4]
From the description of the project I understood that exchanges and blockchains can be used independently of each other
I'm however not able to configure any blockchains without an exchange, it will just refuse to check for updates

Can somebody confirm that that's the case? And maybe what the use case is of the blockchain functionality?

```
--------------------------------------------------------
Trying to connect to your Firefly III account...
Connection to your Firefly III account established.
--------------------------------------------------------
Migration: Checking if there are any account or transaction identifiers to migrate.
Migration: 0 notes of accounts or transactions were migrated.

There are no exchanges configured. Exit!
```

**Comment by financelurker** [comment]
You don't. The public ledger modules is there to capture your deposits/withdrawals to and from the exchange (in case you have auto-withdrawals, or so) from specified addresses on the supported ledger.

It might also be fair to say, that this project isn't maintained, so the exchange API might have changed and this app might be broken as of now.

**Comment by bee395** [comment]
Aha, thanks for the clarification and the quick response!

That's fair, I also had to tweak the code of this project a bit to get it working. Since the firefly client interface changed a bit
